//DS-14 Start
using Content.Shared.Crayon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Crayon.UI;

[GenerateTypedNameReferences]
public sealed partial class CrayonOpacityWindow : DefaultWindow
{
    public event Action<float>? OnOpacity;

    private bool _setting;

    public CrayonOpacityWindow()
    {
        RobustXamlLoader.Load(this);
        OpacitySlider.OnValueChanged += _ =>
        {
            PercentLabel.Text = $"{(int) OpacitySlider.Value}%";
            if (_setting)
                return;

            OnOpacity?.Invoke(OpacitySlider.Value / 100f);
        };
    }

    public void SetOpacity(CrayonComponent crayon)
    {
        _setting = true;
        OpacitySlider.MinValue = crayon.MinOpacity * 100f;
        OpacitySlider.MaxValue = crayon.MaxOpacity * 100f;
        OpacitySlider.Value = crayon.Opacity * 100f;
        PercentLabel.Text = $"{(int) OpacitySlider.Value}%";
        _setting = false;
    }
}
//DS-14 End
